# frozen_string_literal: true
source "https://rubygems.org"

gem "appium_lib"
gem "appium_console"
gem "cpf_faker"
gem "pry"
gem "cucumber"
gem "roo"
gem "faker"
gem "rspec"
gem "credy"
gem "httparty"
gem "flick"
gem "allure-cucumber"
gem "report_builder"
gem "selenium-webdriver"
gem "capybara"
gem "webdrivers"
gem "watir"
gem "rake"
gem "test-unit"
gem "assert"
gem "spreadsheet"
gem "rubyXL"
gem "pdf-reader"

